CONFIG_DIR: ${HOME}/jarvis-pipelines
CUR_PIPELINE: null
HOSTFILE: null
PRIVATE_DIR: /mnt/ssd/${USER}/jarvis-pipelines
REPOS:
- name: builtin
  path: ${HOME}/jarvis-cd/builtin
SHARED_DIR: ${HOME}/jarvis-pipelines